### ISSUE TITLE
Question regarding of parameters

### ISSUE THREAD

**Issue by KaitoHH** [wangjin0818/word_embedding_refine#1]
I have read your paper and have some questions regarding of parameters. In your implementation, you leave `alpha` and `gamma` for users to specify, but I wonder what the optimal parameter is in your experiment, as it takes much time to execute these codes to find the optimal parameter. Would you please share these parameters?

**Comment by jinyueyuan** [comment]
I have the same issue with you. I wonder if the author could tell us. Thanks a lot!

**Comment by pribadihcr** [comment]
@KaitoHH ,

Did you get the optimal parameters?.
